"""Follow the real free cuff and closed mesh sections toward the armhole.

The legacy six-point ``shoulder_polygon`` is an armhole seam, not a free
cuff. The older autogenerated rings extend from that seam into the torso.
Here every interior section is a connected triangle/plane intersection;
its barycentric locations stay on the cloth as it deforms. No polar sorting
of disconnected garment points is used to invent a closed loop.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

from check_pb_cloth_deformation import read_obj


DEFAULT_OBJ = Path('/home/ge47gax/kun/fmvp_pb/dressing_pb/assistive_gym/assets/data/cloth3d/train/Tshirt/tshirt_26.obj')


def cycles(adjacency):
    if any(len(v) != 2 for v in adjacency.values()):
        raise ValueError('Expected disjoint closed degree-two mesh loops')
    unseen = set(adjacency)
    result = []
    while unseen:
        first = min(unseen)
        previous, current, loop = None, first, []
        while current not in loop:
            loop.append(current)
            following = sorted(adjacency[current])
            following = next(v for v in following if v != previous)
            previous, current = current, following
        if current != first:
            raise ValueError('Intersection is not a simple closed loop')
        unseen.difference_update(loop)
        result.append(loop)
    return result


class SleeveSections:
    def __init__(self, vertices, faces, armhole):
        self.vertices = np.asarray(vertices, float)
        self.faces = np.asarray(faces, int)
        self.armhole = np.asarray(armhole, int)
        face_edges = np.sort(np.concatenate([faces[:, [0, 1]], faces[:, [1, 2]], faces[:, [2, 0]]]), axis=1)
        self.edges, counts = np.unique(face_edges, axis=0, return_counts=True)
        boundary = {}
        for a, b in self.edges[counts == 1]:
            boundary.setdefault(int(a), set()).add(int(b))
            boundary.setdefault(int(b), set()).add(int(a))
        loops = cycles(boundary)
        seam_center = vertices[self.armhole].mean(0)
        self.cuff = np.asarray(min(loops, key=lambda ids: np.linalg.norm(vertices[ids].mean(0) - seam_center)), int)
        cuff_center = vertices[self.cuff].mean(0)
        axis = seam_center - cuff_center
        length = np.linalg.norm(axis)
        axis /= length
        self.axis = axis
        self.sections = [(np.stack([self.cuff, self.cuff], axis=1), np.zeros(len(self.cuff)))]
        self.fractions = [0.]
        # Stay on the sleeve side of the seam. Three true cross-sections,
        # plus its free opening, are enough to reject an unthreaded sleeve.
        for fraction in (.25, .5, .75):
            origin = cuff_center + fraction * length * axis
            signed = (vertices - origin) @ axis
            graph = {}
            for face in faces:
                crossed = []
                for a, b in zip(face, np.roll(face, -1)):
                    if signed[a] * signed[b] < 0:
                        crossed.append(tuple(sorted((int(a), int(b)))))
                if len(crossed) == 2:
                    a, b = crossed
                    graph.setdefault(a, set()).add(b)
                    graph.setdefault(b, set()).add(a)
                elif crossed:
                    raise ValueError('Degenerate section plane through a vertex')
            candidates = []
            for loop in cycles(graph):
                edges = np.asarray(loop, int)
                weight = -signed[edges[:, 0]] / (signed[edges[:, 1]] - signed[edges[:, 0]])
                points = vertices[edges[:, 0]] * (1 - weight[:, None]) + vertices[edges[:, 1]] * weight[:, None]
                candidates.append((np.linalg.norm(points.mean(0) - origin), edges, weight))
            if not candidates:
                raise ValueError('No closed sleeve cross-section')
            _, edges, weight = min(candidates, key=lambda c: c[0])
            self.sections.append((edges, weight))
            self.fractions.append(fraction)

    def points(self, cloth):
        return [cloth[edge[:, 0]] * (1 - weight[:, None]) + cloth[edge[:, 1]] * weight[:, None]
                for edge, weight in self.sections]

    def describe(self):
        return dict(cuff_vertex_indices=self.cuff.tolist(), section_fractions=self.fractions,
                    section_point_counts=[len(e) for e, _ in self.sections],
                    armhole_vertex_indices=self.armhole.tolist(),
                    section_rest_centers=[p.mean(0).tolist() for p in self.points(self.vertices)])


def ring_on_arm(ring, landmarks):
    lengths = np.linalg.norm(np.diff(landmarks, axis=0), axis=1)
    center = ring.mean(0)
    choices = []
    for seg, (start, end) in enumerate(zip(landmarks[:-1], landmarks[1:])):
        direction = (end - start) / lengths[seg]
        along = np.dot(center - start, direction)
        nearest = start + np.clip(along, 0, lengths[seg]) * direction
        rel = ring - nearest
        radial = rel - (rel @ direction)[:, None] * direction
        nxt = np.roll(radial, -1, axis=0)
        angles = np.arctan2(np.cross(radial, nxt) @ direction, np.sum(radial * nxt, axis=1))
        winding = abs(float(angles.sum() / (2 * np.pi)))
        radii = np.linalg.norm(radial, axis=1)
        s = (lengths[:seg].sum() + np.clip(along, 0, lengths[seg])) / lengths.sum()
        choices.append(dict(s=float(s), segment=seg, winding=winding,
                            center_distance_m=float(np.linalg.norm(center - nearest)),
                            radial_mean_m=float(radii.mean()), radial_max_m=float(radii.max()),
                            wrapped=bool(winding >= .75 and radii.mean() <= .18 and radii.max() <= .30
                                         and -.01 <= along <= lengths[seg] + .01)))
    minimum = min(c['center_distance_m'] for c in choices)
    nearby = [c for c in choices if c['wrapped'] and c['center_distance_m'] <= minimum + .01]
    return min(nearby or choices, key=lambda c: c['center_distance_m'])


def measure(sections, cloth, landmarks):
    rings = [ring_on_arm(p, landmarks) for p in sections.points(cloth)]
    upper_fraction = ((rings[-1]['s'] * np.linalg.norm(np.diff(landmarks, axis=0), axis=1).sum()
                       - np.linalg.norm(landmarks[1] - landmarks[0]))
                      / np.linalg.norm(landmarks[2] - landmarks[1]))
    return dict(sleeve_wrapped=all(r['wrapped'] for r in rings),
                cuff_s=rings[0]['s'], proximal_upper_fraction=float(upper_fraction), rings=rings)


def first_window(mask, hold):
    for k in range(len(mask) - hold):
        if np.all(mask[k:k + hold + 1]):
            return k
    return None


def audit(path, vertices, faces, hold):
    with np.load(path, allow_pickle=False) as data:
        metadata = json.loads(str(data['metadata_json']))
        if metadata.get('collision_geometry') != 'full_body' or 'human_vertices' not in data:
            raise ValueError(f'Full-body recording required: {path}')
        if not np.array_equal(data['faces'], faces):
            # Face ordering/winding may differ, but the actual triangles must agree.
            a = set(map(tuple, np.sort(data['faces'], axis=1)))
            b = set(map(tuple, np.sort(faces, axis=1)))
            if a != b:
                raise ValueError(f'Wrong template topology: {path}')
        sections = SleeveSections(vertices, faces, data['opening_idx'])
        landmarks = np.stack([data[k] for k in ['finger', 'elbow', 'shoulder']])
        cloth = data['positions']
        measurements = [measure(sections, p, landmarks) for p in cloth]
        wrapped = np.asarray([m['sleeve_wrapped'] for m in measurements])
        # Retain the original task completion threshold, while checking the
        # real sleeve tube rather than rings on the shirt torso.
        complete = wrapped & (data['upperarm_ratio'] >= .7)
        start = first_window(complete, hold)
        valid = bool(data['grasp_valid'].all())
        failure = metadata.get('sim_error')
        edges = sections.edges
        initial = np.linalg.norm(cloth[0, edges[:, 0]] - cloth[0, edges[:, 1]], axis=1)
        ratio = np.linalg.norm(cloth[:, edges[:, 0]] - cloth[:, edges[:, 1]], axis=2) / initial
        peak = np.linalg.norm(data['gripper_force'], axis=1)
        return dict(path=str(path.resolve()), sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
                    body=metadata['body'], transitions=len(data['actions']),
                    held_complete_start=start, held_complete=start is not None,
                    valid_grasp=valid, geometry_and_grasp_pass=bool(start is not None and valid),
                    accepted=bool(start is not None and valid and not failure), failure=failure,
                    wrapped_states=int(wrapped.sum()), upperarm_ratio_final=float(data['upperarm_ratio'][-1]),
                    gripper_peak_N=float(peak.max()), edge_p99_peak_vs_initial=float(np.quantile(ratio, .99, axis=1).max()),
                    edge_max_peak_vs_initial=float(ratio.max()),
                    complete_state=measurements[start] if start is not None else None,
                    final=measurements[-1], sections=sections.describe())


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('episodes', nargs='+', type=Path)
    p.add_argument('--obj', type=Path, default=DEFAULT_OBJ)
    p.add_argument('--hold', type=int, default=5)
    p.add_argument('--out', type=Path, required=True)
    a = p.parse_args()
    vertices, faces = read_obj(a.obj)
    vertices *= 4.
    rows = [audit(path, vertices, faces, a.hold) for path in a.episodes]
    report = dict(method='actual free cuff plus three connected mesh-plane sections on the sleeve side of the armhole',
                  previous_error='legacy right_cuff_loop_ordered is the armhole seam; its generated rings extend into the torso',
                  geometry_and_grasp_passes=sum(r['geometry_and_grasp_pass'] for r in rows),
                  accepted=sum(r['accepted'] for r in rows),
                  attempts=len(rows), hold_decisions=a.hold, obj_sha256=hashlib.sha256(a.obj.read_bytes()).hexdigest(),
                  qualification='simulation sleeve completion; forces and material are not calibrated to hardware', episodes=rows)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(json.dumps(report, indent=2) + '\n')
    for r in rows:
        print(Path(r['path']).parent.name, Path(r['path']).stem,
              'complete', r['held_complete_start'], 'grasp', r['valid_grasp'],
              'edge_p99', round(r['edge_p99_peak_vs_initial'], 3))
    print('Geometry and grasp:', report['geometry_and_grasp_passes'], '/', len(rows))


if __name__ == '__main__':
    main()
