"""Maintain a readable evidence report while the single simulation worker runs."""
from __future__ import annotations

import argparse
import datetime
import json
import os
from pathlib import Path
import time

from run_sim2real_audit import DEFAULT_OUT, ROOT


def interval(value):
    if value["mean"] is None:
        return "—"
    lo, hi = value["bootstrap95"]
    return f"{100 * value['mean']:+.1f} [{100 * lo:+.1f}, {100 * hi:+.1f}]"


def render(out, target):
    protocol = json.loads((out / "protocol.json").read_text())
    state = json.loads((out / "status.json").read_text())
    summary = json.loads((out / "summary.json").read_text())
    try:
        os.kill(state["supervisor_pid"], 0)
        alive = True
    except ProcessLookupError:
        alive = False
    completed = summary["completed_batches"]
    lines = ["# Sim-to-real robustness screen — generated results", "",
             "Generated by `scripts/wang_transfer/report_sim2real_audit.py`; do not edit this file manually.", "",
             f"Updated: {datetime.datetime.now(datetime.timezone.utc).isoformat()}.", "",
             f"State: **{state['stage']}**; supervisor PID {state['supervisor_pid']} "
             f"({'alive' if alive else 'exited'}). Completed batches: **{completed}/{len(protocol['jobs'])}**.", "",
             "[Research study and method candidate](2026-10-05-sim2real-posttraining-study.md). "
             "Protocol, raw trajectories, hashes, resource events and machine-readable results: "
             "`output/uipc_manip/sim2real_audit_20261005/`.", "",
             "Seven development bodies, one garment, three frozen policies. A row is paired only "
             "when all three policies have completed with matching initial geometry. Missing jobs "
             "are not failures. Grasp loss is a task failure. No real robot is measured.", "",
             "## Success counts", "",
             "| Condition | Paired cases | fmvp_sim | r1 | flow |", "|---|---:|---:|---:|---:|"]
    for c, row in summary["conditions"].items():
        n = row["paired_units"]
        counts = [f"{row['successes'][p]}/{n}" if n else "pending" for p in ("fmvp_sim", "r1", "flow")]
        lines.append(f"| {c} | {n} | " + " | ".join(counts) + " |")
    lines += ["", "## Paired gain over fmvp_sim", "",
              "Gains and changes are percentage points; brackets are pointwise 95% percentile "
              "bootstrap intervals over bodies. The exact McNemar test concerns each policy's "
              "gain within a condition, not the change in gain between conditions.", "",
              "| Condition | Policy | Wins:losses | Exact p | Gain [CI] | Change from nominal [CI] |",
              "|---|---|---:|---:|---:|---:|"]
    for c, row in summary["conditions"].items():
        if not row["paired_units"]:
            continue
        for p, value in row["comparisons"].items():
            lines.append(f"| {c} | {p} | {value['wins']}:{value['losses']} | "
                         f"{value['exact_mcnemar_p']:.4g} | {interval(value['gain'])} | "
                         f"{interval(value['gain_change_from_nominal'])} |")
    lines += ["", "## Identical nominal repeat", ""]
    for p, r in summary["repeatability"].items():
        agreement = r["agreement"]["mean"]
        lines.append(f"- {p}: {r['units']} paired repeat cases; agreement "
                     + (f"{100 * agreement:.1f}%." if agreement is not None else "pending."))
    cost = summary["cost"]
    lines += ["", "## Cost and interpretation limits", "",
              f"- Finished/terminated worker attempts: {cost['attempts']}; charged time "
              f"{cost['worker_seconds'] / 3600:.2f} worker-hours. The currently active attempt is not yet in this total.",
              f"- Recorded peak total GPU use in finished attempts: {cost['peak_total_gpu_mib']} MiB.",
              "- Small-sample exploratory screen. A zero-width bootstrap interval from identical observed "
              "differences is a resampling degeneracy, not certainty about the population. No equivalence "
              "or multiple-comparison discovery claim follows from nonsignificance.",
              "- No unit, garment, or perturbation was selected after inspecting this screen.",
              "- Parameter fragility does not by itself prove simulator exploitation; parameter robustness "
              "does not establish hardware transfer. Density/thickness also change the grasp penalty, and "
              "flow uses simulated gripper force.",
              "- The nominal repeat is a repeatability check, not seven additional independent bodies.", ""]
    if not summary["complete"]:
        lines += ["**Incomplete:** do not draw a final gain-retention conclusion from this report yet.", ""]
    else:
        lines += ["All predeclared batches finished. Use gain-change intervals and repeatability together; "
                  "this pilot alone is insufficient to certify transfer.", ""]
    target.parent.mkdir(parents=True, exist_ok=True)
    temp = target.with_suffix(".tmp")
    temp.write_text("\n".join(lines))
    temp.replace(target)
    return summary["complete"] or not alive or state["stage"] in {
        "memory_guard", "worker_error", "incomplete_job", "worker_budget_reached", "stopped_by_request", "needs_inspection"}


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    p.add_argument("--target", type=Path, default=ROOT / "agent_docs/performance/2026-10-05-sim2real-robustness-results.md")
    p.add_argument("--watch", action="store_true")
    a = p.parse_args()
    while True:
        finished = render(a.out, a.target)
        if finished or not a.watch:
            return
        time.sleep(30)


if __name__ == "__main__":
    main()
